PatientsDashboard/Controllers/DrugsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PatientsDashboard.Models;
using System;
using PatientsDashboard.ActionFilters;
using log4net;

namespace PatientsDashboard.Controllers
{
    [Authorize]
    //[OutputCache(Duration = 480, VaryByParam = "none")]
    [CompressFilter]
    [ETag]
    public class DrugsController : Controller
    {
        ProcedureModels _entities = new ProcedureModels();
        private static readonly ILog Logger = LogManager.GetLogger(System.Environment.MachineName);
        // GET: Most recent drugs purchased by the user and display a drop down of the visits, allowing the user to select any visit to display the results
        public ActionResult PatientDrugsView()
        {
            return View();
        }

        public ActionResult _DrugsView(string cycle)
        {
            string user = Session["patientID"].ToString();
            Logger.Info(user);
            Logger.Debug("Accessing patient drugs");
            
          
            //Call the drugs procedure
            List<PatientDrugs_Result> drugList = _entities.PatientDrugs(cycle).OrderByDescending(c => c.trans_date).ToList();
            List<PatientDrugs_Result> list = new List<PatientDrugs_Result>();
            foreach (var item in drugList)
            {
                var newItem = new PatientDrugs_Result();
                newItem.center_product_description = item.center_product_description;
                newItem.cycle_id = item.cycle_id;
                newItem.product_code = item.product_code;
                newItem.unit_price = item.unit_price;
                newItem.trans_quantity = item.trans_quantity;
                newItem.total = Convert.ToDecimal(newItem.trans_quantity) * newItem.unit_price;
                newItem.trans_date = item.trans_date;
                newItem.regular_retail_price = item.regular_retail_price;
                newItem.vatvalue = item.vatvalue;
                newItem.savings = item.savings;
                list.Add(newItem);
            }

            //Summarize totals, savings and %Savings

            var summary = list.AsEnumerable();

            if (summary.Sum(c => c.total).HasValue)
            {
                ViewBag.Total = $"{summary.Sum(c => c.total):#,###0}";
            }
            else
            {
                ViewBag.Total = 0;
            }


            var savings = summary.Sum(c => c.savings);
            if (!savings.HasValue)
            {
                savings = 0;
            }

            var regularTotal = summary.Sum(c => c.regular_retail_price);
            if (savings != 0 && regularTotal != 0)
            {
                var percentageSavings = (savings / regularTotal) * 100;
                ViewBag.PercentageSavings = $"{percentageSavings:#,###0}";
            }
            else
            {
                var percentageSavings = 0;
                ViewBag.PercentageSavings = percentageSavings;
            }


            ViewBag.Savings = $"{savings:#,###0}";
            if (drugList.Any())
            {
                return PartialView("_DrugsView", list);
            }
            else
            {
                return Content("");
            }



            

        }
    }
}

PatientsDashboard/Controllers/VitalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PatientsDashboard.ActionFilters;
using PatientsDashboard.Models;
using log4net;

namespace PatientsDashboard.Controllers
{
    [Authorize]
    //[OutputCache(Duration = 480, VaryByParam = "none")]
    [CompressFilter]
    [ETag]
    public class VitalsController : Controller
    {
        ProcedureModels _entities = new ProcedureModels();
        private static readonly ILog Logger = LogManager.GetLogger(System.Environment.MachineName);
        // GET: Vitals
        public ActionResult VitalsView()
        {
            return View();
        }

        public JsonResult getVisits()
        {
            var visits = _entities.PatientVisits(Session["patientID"].ToString()).OrderByDescending(c => DateTime.Parse(c.cycle_created_time.ToString()).Date).ToList();
            List<PatientVisits_Result> list = new List<PatientVisits_Result>();
            foreach (var item in visits)
            {
                var cycles = new PatientVisits_Result();
                cycles.visitDate = string.Format("{0:dd-MM-yyyy}", item.cycle_created_time);
                cycles.cycle_id = item.cycle_id;
                list.Add(cycles);

            }

            return Json(list, JsonRequestBehavior.AllowGet);
        }
        //Get Vitals based on the Visit Date Selected

        [HttpPost]
        public ActionResult _Vitals(string cycle)
        {
            
            string user = Session["patientID"].ToString();
            Logger.Info(user);
            Logger.Debug("Accessing patient vitals");
            var vitals = _entities.PatientVitalsProc(cycle).ToList();
            if (vitals.Any())
            {
                return PartialView("_Vitals", vitals);
            }
            else
            {
                return Content("");
            }
            

        }

    }
}

PatientsDashboard/Views/Drugs/PatientDrugsView.cshtml
@model IEnumerable<PatientsDashboard.Models.PatientDrugs_Result>
@{
    ViewBag.Title = "CheckUps | Drugs";
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Drugs Purchased</h3>
        @using (Ajax.BeginForm("VitalsView", "Vitals", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "#ajaxDrugs" }))
        {
            @Html.AntiForgeryToken()
            <br />
           
            <select class="form-control" id="visitsDropDown">
               
            </select>

        }
    </div>

    <div id="ajaxDrugs">

    </div>

</div>
@section Scripts
{
    <script type="text/javascript">

        $(function () {

            AjaxCall('@Url.Action("getVisits","Vitals")', null).done(function (response) {
                if (response.length > 0) {
                    $('#visitsDropDown').html('');
                    var options = '';
                    options += '<option value="" disabled selected>Select Visit Date</option>';
                    for (var i = 0; i < response.length; i++) {
                        options += '<option value="' + response[i].cycle_id + '">' + response[i].visitDate + '</option>';
                    }
                    $('#visitsDropDown').append(options);
                     //get the latest visit loaded on the view by default
                    $('#visitsDropDown option').each(function ()
                    {
                        var cycle = this.value;
                        var flag = true;
                        var obj = { cycle: cycle };
                        AjaxCall('@Url.Action("_DrugsView","Drugs")', JSON.stringify(obj), 'POST').done(function (data) {

                            if (data.length > 0) {
                                $('#ajaxDrugs').html(data);
                                flag = false;
                                return false;
                            }
                        });
                        return flag;
                    });

                }
            }).fail(function (error) {
                alert(error.StatusText);
            });

            $('#visitsDropDown').on("change", function () {

                var cycle = $('#visitsDropDown').val();
                var visitDate = $('#visitsDropDown option:selected').text();
                var obj = { cycle: cycle };
                AjaxCall('@Url.Action("_DrugsView","Drugs")', JSON.stringify(obj), 'POST').done(function (response) {
                    if (response.length > 0) {
                        $('#ajaxDrugs').html(response);
                    }
                    else
                    {
                        alert('You did not get any drug prescriptions on ' + visitDate);
                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
            });

        });

        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                contentType: 'application/json'
            });
        }

    </script>
}

PatientsDashboard/Views/Drugs/_DrugsView.cshtml
@model IEnumerable<PatientsDashboard.Models.PatientDrugs_Result>

<div class="box-body">

    <table class="table table-bordered">
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th>
                Total: @ViewBag.Total
            </th>
            <th>
                Savings:@ViewBag.Savings
            </th>
            <th>
                % Savings: @ViewBag.PercentageSavings %
            </th>
        </tr>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.trans_date)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.center_product_description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.trans_quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.unit_price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vatvalue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.regular_retail_price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.savings)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.trans_date)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.center_product_description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.trans_quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.unit_price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vatvalue)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.regular_retail_price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.savings)
                </td>

            </tr>
        }

    </table>
</div>