PatientsDashboard/Controllers/LabTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PatientsDashboard.ActionFilters;
using PatientsDashboard.Models;
using PatientsDashboard.ViewModels;
using log4net;
using System.Text;

namespace PatientsDashboard.Controllers
{
    [Authorize]
    [CompressFilter]
    [ETag]

    public class LabTestController : Controller
    {
        ProcedureModels _entities = new ProcedureModels();
        private static readonly ILog Logger = LogManager.GetLogger(System.Environment.MachineName);
        // GET: LabTest
        public ActionResult LabTestView()
        {

            return View();
        }
        public ActionResult _labResults(string cycle)
        {

           
        
            string user = Session["patientID"].ToString();
            Logger.Info(user);
            Logger.Debug("Accessing patient labs");
            StringBuilder stringBuilder = new StringBuilder();
            List<PatientLabResults_Result> labResults = _entities.PatientLabResults(cycle).OrderByDescending(c => c.cycle_created_time).OrderBy(c => c.TEST).ToList();
            List<PatientNotes_Result> patientNotes = _entities.PatientNotes(cycle).OrderBy(c => c.notes_date).ToList();
            List<PatientNotes_Result> final = new List<PatientNotes_Result>();
            foreach (var item in patientNotes)
            {
                if ((item.notes_desc.ToLower().Contains("lab")) && (item.notes_desc.ToLower().Contains("results")) || (item.notes_desc.ToLower().Contains("recommendations")))
                {
                    stringBuilder.Append(item.notes_desc);
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine();
                }
                final.Add(item);

            }
            ViewBag.recommendations = stringBuilder.ToString();

            var view = new LabNotesViewModel
            {

                PatientNotes = final,
                PatientLabs = labResults

            };

            return PartialView("_labResults", view);
        }
    }
}

PatientsDashboard/Controllers/VitalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PatientsDashboard.ActionFilters;
using PatientsDashboard.Models;
using log4net;

namespace PatientsDashboard.Controllers
{
    [Authorize]
    //[OutputCache(Duration = 480, VaryByParam = "none")]
    [CompressFilter]
    [ETag]
    public class VitalsController : Controller
    {
        ProcedureModels _entities = new ProcedureModels();
        private static readonly ILog Logger = LogManager.GetLogger(System.Environment.MachineName);
        // GET: Vitals
        public ActionResult VitalsView()
        {
            return View();
        }

        public JsonResult getVisits()
        {
            var visits = _entities.PatientVisits(Session["patientID"].ToString()).OrderByDescending(c => DateTime.Parse(c.cycle_created_time.ToString()).Date).ToList();
            List<PatientVisits_Result> list = new List<PatientVisits_Result>();
            foreach (var item in visits)
            {
                var cycles = new PatientVisits_Result();
                cycles.visitDate = string.Format("{0:dd-MM-yyyy}", item.cycle_created_time);
                cycles.cycle_id = item.cycle_id;
                list.Add(cycles);

            }

            return Json(list, JsonRequestBehavior.AllowGet);
        }
        //Get Vitals based on the Visit Date Selected

        [HttpPost]
        public ActionResult _Vitals(string cycle)
        {
            
            string user = Session["patientID"].ToString();
            Logger.Info(user);
            Logger.Debug("Accessing patient vitals");
            var vitals = _entities.PatientVitalsProc(cycle).ToList();
            if (vitals.Any())
            {
                return PartialView("_Vitals", vitals);
            }
            else
            {
                return Content("");
            }
            

        }

    }
}

PatientsDashboard/Views/LabTest/LabTestView.cshtml
@model IEnumerable<PatientsDashboard.Models.PatientLabResults_Result>
@{
    ViewBag.Title = "CheckUps | Lab";
}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Lab Tests</h3>
        @using (Ajax.BeginForm("VitalsView", "Vitals", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "#ajaxVitals" }))
        {
            @Html.AntiForgeryToken()

            <br />
            @*<label class="col-md-6">Visits</label>*@
            <select class="form-control" id="visitsDropDown">
            </select>

        }
    </div>

    <div id="ajaxLabs">

    </div>

</div>
@section Scripts
{
    <script type="text/javascript">

        $(function () {
            //Populate visits cycle dates to the front end, these visits are pulled from the vitals controller
            AjaxCall('@Url.Action("getVisits","Vitals")', null).done(function (response) {
                if (response.length > 0) {
                    $('#visitsDropDown').html('');
                    var options = '';
                    options += '<option value="" disabled selected>Select Visit Date</option>';
                    for (var i = 0; i < response.length; i++) {
                        options += '<option value="' + response[i].cycle_id + '">' + response[i].visitDate + '</option>';
                    }
                    $('#visitsDropDown').append(options);
                     //get the latest visit loaded on the view by default
                    $('#visitsDropDown option').each(function ()
                    {
                        var cycle = this.value;
                        var flag = true;
                        var obj = { cycle: cycle };
                        AjaxCall('@Url.Action("_labResults","LabTest")', JSON.stringify(obj), 'POST').done(function (data) {

                            if (data.length > 0) {
                                $('#ajaxLabs').html(data);
                                flag = false;
                                return false;
                            }
                           
                        });

                        return flag;

                    });

                }
            }).fail(function (error) {
                alert(error.StatusText);
            });

            //load different visits when user selects specific visit cyles
            $('#visitsDropDown').on("change", function () {

                var cycle = $('#visitsDropDown').val();
                var visitDate = $('#visitsDropDown option:selected').text();
                var obj = { cycle: cycle };
                AjaxCall('@Url.Action("_labResults","LabTest")', JSON.stringify(obj), 'POST').done(function (response) {
                    if (response.length > 0)
                    {
                        $('#ajaxLabs').html(response);
                    }
                    else
                    {
                        alert('You did not have lab tests on ' + visitDate);
                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
            });

        });

        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                contentType: 'application/json'
            });
        }

    </script>
}

PatientsDashboard/Views/LabTest/_labResults.cshtml
@model  PatientsDashboard.ViewModels.LabNotesViewModel
<div class="box-body">
    @if (Model.PatientNotes.Any())
    {
        <p><b>Recommendations </b></p>
        <p>
            <textarea readonly="readonly" rows="10" cols="40">
@ViewBag.recommendations
</textarea>
        </p>

            @*<p>@Html.T(, 10, 40, new { @readonly = "readonly" })</p>*@
        
    }
    @if (Model.PatientLabs.Any())
    {


        <table class="table table-bordered" style="table-layout: fixed;">
            <tr>
                <th>DATE</th>
                <th>TEST</th>
                <th>RESULT</th>
                <th>VALUE</th>
                <th>REF</th>
                <th>STATUS</th>
            </tr>
            @foreach (var item in Model.PatientLabs)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.cycle_created_time)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TEST)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.RESULT)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VALUE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.REF)
                    </td>
                    @if (item.STATUS == "HIGHER")
                    {
                        <td>

                            <font color="red">@Html.DisplayFor(modelItem => item.STATUS)</font>
                        </td>
                    }
                    else if (item.STATUS == "NORMAL")
                    {
                        <td>

                            <font color="green">@Html.DisplayFor(modelItem => item.STATUS)</font>
                        </td>
                    }
                    else
                    {
                        <td>

                            <font color="orange">@Html.DisplayFor(modelItem => item.STATUS)</font>
                        </td>
                    }


                </tr>
            }
        </table>
    }


</div>