PatientsDashboard/Controllers/VisitSummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PatientsDashboard.ActionFilters;
using PatientsDashboard.Models;
using PatientsDashboard.ViewModels;
using log4net;

namespace PatientsDashboard.Controllers
{
    [Authorize]
    //[OutputCache(Duration = 480, VaryByParam = "none")]
    [CompressFilter]
    [ETag]
    public class VisitSummaryController : Controller
    {
        ProcedureModels _entities = new ProcedureModels();
        private static readonly ILog Logger = LogManager.GetLogger(System.Environment.MachineName);
        // GET: Vitals
        // GET: VisitSummary
        public ActionResult VisitSummaryView()
        {

            return View();

        }
        public ActionResult _VisitSummaries(string cycle)
        {

            string user = Session["patientID"].ToString();
            Logger.Info(user);
            Logger.Debug("Accessing patient visit summary");
            List<PatientVitalsProc_Result> patientVitals = _entities.PatientVitalsProc(cycle).ToList();
            List<PatientSigns_Result> patientSigns = _entities.PatientSigns(cycle).ToList();
            List<PatientSymptoms_Result> patientSymptoms = _entities.PatientSymptoms(cycle).ToList();
            List<PatientNotes_Result> patientNotes = _entities.PatientNotes(cycle).ToList();
            List<PatientDiagnosis_Result> patientDiagnosis = _entities.PatientDiagnosis(cycle).ToList();
            List<PatientDrugs_Result> patientDrugs = _entities.PatientDrugs(cycle).ToList();
            List<PatientDrugs_Result> list = new List<PatientDrugs_Result>();
            foreach (var item in patientDrugs)
            {
                var newItem = new PatientDrugs_Result();
                newItem.center_product_description = item.center_product_description;
                newItem.cycle_id = item.cycle_id;
                newItem.product_code = item.product_code;
                newItem.unit_price = item.unit_price;
                newItem.trans_quantity = item.trans_quantity;
                newItem.total = Convert.ToDecimal(newItem.trans_quantity) * newItem.unit_price;
                newItem.trans_date = item.trans_date;
                newItem.regular_retail_price = item.regular_retail_price;
                newItem.vatvalue = item.vatvalue;
                newItem.savings = item.savings;
                list.Add(newItem);
            }
            VisitViewModel view = new VisitViewModel
            {

                PatientVitals = patientVitals,
                PatientNotes = patientNotes,
                PatientDiagnosis = patientDiagnosis,
                PatientSigns = patientSigns,
                PatientSymptoms = patientSymptoms,
                PatientTreatment = list
            };
            return PartialView("_VisitSummaries", view);
        }
            


    }
}

PatientsDashboard/Controllers/VitalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PatientsDashboard.ActionFilters;
using PatientsDashboard.Models;
using log4net;

namespace PatientsDashboard.Controllers
{
    [Authorize]
    //[OutputCache(Duration = 480, VaryByParam = "none")]
    [CompressFilter]
    [ETag]
    public class VitalsController : Controller
    {
        ProcedureModels _entities = new ProcedureModels();
        private static readonly ILog Logger = LogManager.GetLogger(System.Environment.MachineName);
        // GET: Vitals
        public ActionResult VitalsView()
        {
            return View();
        }

        public JsonResult getVisits()
        {
            var visits = _entities.PatientVisits(Session["patientID"].ToString()).OrderByDescending(c => DateTime.Parse(c.cycle_created_time.ToString()).Date).ToList();
            List<PatientVisits_Result> list = new List<PatientVisits_Result>();
            foreach (var item in visits)
            {
                var cycles = new PatientVisits_Result();
                cycles.visitDate = string.Format("{0:dd-MM-yyyy}", item.cycle_created_time);
                cycles.cycle_id = item.cycle_id;
                list.Add(cycles);

            }

            return Json(list, JsonRequestBehavior.AllowGet);
        }
        //Get Vitals based on the Visit Date Selected

        [HttpPost]
        public ActionResult _Vitals(string cycle)
        {
            
            string user = Session["patientID"].ToString();
            Logger.Info(user);
            Logger.Debug("Accessing patient vitals");
            var vitals = _entities.PatientVitalsProc(cycle).ToList();
            if (vitals.Any())
            {
                return PartialView("_Vitals", vitals);
            }
            else
            {
                return Content("");
            }
            

        }

    }
}

PatientsDashboard/Views/VisitSummary/VisitSummaryView.cshtml
@model  PatientsDashboard.ViewModels.VisitViewModel
@if (Request.IsAuthenticated)
{
    ViewBag.Title = "CheckUps | Visit Summary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Visit Summary</h3>
        @using (Ajax.BeginForm("VitalsView", "Vitals", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "#ajaxVitals" }))
        {
            @Html.AntiForgeryToken()
            <br />
            <select class="form-control" id="visitsDropDown">
            </select>

        }
    </div>
    <div id="ajaxVisitSummaries">

    </div>

</div>
@section Scripts
{
    <script type="text/javascript">

        $(function () {

            AjaxCall('@Url.Action("getVisits","Vitals")', null).done(function (response) {
                if (response.length > 0) {
                    $('#visitsDropDown').html('');
                    var options = '';
                    options += '<option value="" disabled selected>Select Visit Date</option>';
                    for (var i = 0; i < response.length; i++) {
                        options += '<option value="' + response[i].cycle_id + '">' + response[i].visitDate + '</option>';
                    }
                    $('#visitsDropDown').append(options);
                      //get the latest visit loaded on the view by default
                    $('#visitsDropDown option').each(function ()
                    {
                        var cycle = this.value;
                        var flag = true;
                        var obj = { cycle: cycle };
                        AjaxCall('@Url.Action("_VisitSummaries","VisitSummary")', JSON.stringify(obj), 'POST').done(function (data) {

                            if (data.length > 0) {
                                $('#ajaxVisitSummaries').html(data);
                                flag = false;
                                return false;
                            }
                           
                        });

                        return flag;

                    });

                }
            }).fail(function (error) {
                alert(error.StatusText);
            });

            $('#visitsDropDown').on("change", function () {

                var cycle = $('#visitsDropDown').val();
                var visitDate = $('#visitsDropDown option:selected').text();
                var obj = { cycle: cycle };
                AjaxCall('@Url.Action("_VisitSummaries","VisitSummary")', JSON.stringify(obj), 'POST').done(function (response) {
                    if (response.length > 0) {
                        $('#ajaxVisitSummaries').html(response);
                    }
                    else
                    {
                        alert('You did not have a visit on ' + visitDate);
                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
            });

        });

        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                contentType: 'application/json'
            });
        }

    </script>
}